# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p@ssw0rd
    networks:
      - reactive_spring

  spring-reactive:
    build: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - reactive_spring
    depends_on:
      - mongodb

networks:
  reactive_spring:
    driver: bridge
